In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [14]:
df=pd.read_csv('Warsaw_rent_cleaned.csv')
df.head()

squareMeters  rooms   latitude  longitude  centreDistance  poiCount  \
0          47.0    2.0  52.257912  20.968610            3.76      33.0   
1          27.0    1.0  52.249800  21.035200            2.95      33.0   
2          51.0    2.0  52.222864  21.009959            1.08      85.0   
3          50.0    3.0  52.224948  21.012136            0.95     124.0   
4          39.8    2.0  52.216513  21.041474            3.09       6.0   

   hasParkingSpace  hasBalcony  hasSecurity  hasStorageRoom  year  month  \
0                1           1            0               0  2023     11   
1                1           1            0               0  2023     11   
2                0           1            0               0  2023     11   
3                0           0            0               0  2023     11   
4                0           0            0               0  2023     11   

   price  
0   5000  
1   2950  
2   3700  
3   5000  
4   4500

In [15]:
from sklearn.model_selection import train_test_split
X=df.drop('price', axis=1)
y=df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [17]:

predictions = dtree.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
#wieloklasowa klasyfikacja
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

[[4 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 8]]


              precision    recall  f1-score   support

        2400       0.25      0.33      0.29        12
        2440       0.00      0.00      0.00         1
        2450       0.00      0.00      0.00         1
        2480       1.00      1.00      1.00         1
        2490       0.00      0.00      0.00         3
        2499       0.00      0.00      0.00         0
        2500       0.34      0.44      0.38        34
        2550       0.00      0.00      0.00         2
        2600       0.50      0.36      0.42        22
        2650       0.50      0.50      0.50         2
        2700       0.25      0.23      0.24        26
        2750       0.17      0.20      0.18         5
        2790       0.00      0.00      0.00         0
        2800       0.40      0.40      0.40        52
        2850       1.00      1.00      1.00         1
        2899 

c:\Users\julia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\julia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\julia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\julia\anaconda3\lib\site-packages\sklearn\metrics\_cla